from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from typing import List, Optional
from app.langgraph.workflow import compile_workflow
from app.services.memory_service import memory_manager

router = APIRouter(prefix="/chat", tags=["Chat"])

class ChatQueryRequest(BaseModel):
    question: str
    session_id: str = "default"
    top_k: int = Field(default=5, ge=1, le=10)
    temperature: float = Field(default=0.3, ge=0.0, le=1.0)
    llm_provider: str = Field(default="gemini", description="Supported: 'gemini' or 'nvidia'")

class SourceCitation(BaseModel):
    document_name: str
    page_number: Optional[int] = None
    section: Optional[str] = None
    chunk_id: str
    relevance_score: float

class ChatQueryResponse(BaseModel):
    answer: str
    session_id: str
    sources: List[SourceCitation]
    llm_provider: str

# Compile the 9-node workflow graph
workflow = compile_workflow()

@router.post("/query", response_model=ChatQueryResponse)
async def query_chat(payload: ChatQueryRequest):
    try:
        # Initialize LangGraph state matching Section 9 functional requirements
        initial_state = {
            "messages": [("user", payload.question)],
            "question": payload.question,
            "session_id": payload.session_id,
            "top_k": payload.top_k,
            "temperature": payload.temperature,
            "llm_provider": payload.llm_provider,
            "retrieved_chunks": [],
            "reranked_chunks": [],
            "citations": []
        }
        
        # Execute the LangGraph orchestrated workflow state machine
        final_state = await workflow.ainvoke(initial_state)
        
        return ChatQueryResponse(
            answer=final_state.get("answer", "No response generated by workflow."),
            session_id=final_state.get("session_id", payload.session_id),
            sources=final_state.get("citations", []),
            llm_provider=final_state.get("llm_provider", payload.llm_provider)
        )
        
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LangGraph execution faulted: {str(e)}"
        )

@router.get("/history", response_model=List[dict])
async def get_chat_history(session_id: str):
    """Retrieve conversation history for a specific session."""
    try:
        history = memory_manager.get_history(session_id)
        return history
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to connect to Redis: {str(e)}"
        )